// <auto-generated />
namespace CHHC.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CaseConference : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CaseConference));
        
        string IMigrationMetadata.Id
        {
            get { return "201408011655357_CaseConference"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
