// <auto-generated />
namespace CHHC.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CaseConferenceStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CaseConferenceStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201408251953314_CaseConferenceStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
