// <auto-generated />
namespace CHHC.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TrainingInstructorName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrainingInstructorName));
        
        string IMigrationMetadata.Id
        {
            get { return "201403141714119_TrainingInstructorName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
