// <auto-generated />
namespace CHHC.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Blog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Blog));
        
        string IMigrationMetadata.Id
        {
            get { return "201604292332543_Blog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
