INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (109,'Telman A')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (89,'Donara A')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (133,'James H. B')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (136,'Lorene C. B')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (129,'Janet B')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (34,'Yevdokiya B')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (103,'Liza B')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (11,'Lyudmila B')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (17,'Anna B')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (97,'Halina B')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (140,'Edwin C')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (15,'Bella N. C')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (117,'Janice C')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (110,'Lena C')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (82,'Jenniffer C')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (115,'Carmela D')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (134,'Lyubov D')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (143,'Patricia D')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (60,'Yevgeny D')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (141,'Dmitri J. D')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (131,'Anna M. D')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (122,'George F')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (135,'Jeanette C. G')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (53,'Fatemeh G')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (146,'Maureen E. G')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (106,'Lois G')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (32,'Igor B. G')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (84,'Jesus I')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (128,'Tamara I')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (48,'Ninel I')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (76,'Paulina I')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (100,'Joan J')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (150,'Maks K')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (46,'Galina K')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (47,'Ilya K')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (19,'Sonia K')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (65,'Maria L')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (144,'Stasia L')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (145,'Daniil L')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (20,'Daniel L')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (8,'Sofiya L')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (123,'Maryann M')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (108,'Isabel M')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (111,'Olga I. M')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (63,'Jana M')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (148,'Inna M')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (49,'Kathleen M')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (149,'Dorene B. M')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (94,'Yana R. M')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (105,'Joaquina M')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (40,'Lina N')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (39,'Pavel N')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (80,'Catalina N')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (81,'Luis R. N')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (29,'Deva G. O')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (147,'Manuel J. O')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (118,'Maria B. O')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (44,'Galina P')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (1,'Zhanna P')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (10,'Georgiy A. P')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (41,'Pavel G. P')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (45,'Galina R')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (26,'Mariya M. R')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (56,'Ella R')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (138,'Martial P. R')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (137,'Mary T. R')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (101,'Shirley S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (64,'Tsilya V. S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (142,'Emma I. S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (33,'Asya S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (25,'Yakov S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (85,'Liya S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (91,'Yevsey S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (132,'Jenny S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (127,'Anna G. S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (23,'Anatoly S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (57,'Abram K. S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (14,'Yuriy S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (62,'Galina S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (116,'Hyman B. S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (107,'Shirley S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (61,'Kelly E. S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (24,'Emiliya S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (124,'Faith A. S')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (139,'Barbara M. T')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (90,'Asya T')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (88,'Ernesto T')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (43,'Marina N. U')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (28,'Lev Z. U')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (27,'Naum Z. U')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (119,'Loraine U')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (125,'Wayne S. U')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (98,'Carol V')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (79,'Irma V')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (31,'Lyudmila I. V')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (51,'Beatrice W')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (38,'Vitaliy Y')
INSERT INTO [dbo].[Patients] ([InnerChhcId] ,[Name]) VALUES (37,'Nina Y')
