// <auto-generated />
namespace CHHC.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BeforeUserProfileInnerChhcId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BeforeUserProfileInnerChhcId));
        
        string IMigrationMetadata.Id
        {
            get { return "201407050032245_BeforeUserProfileInnerChhcId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
