// <auto-generated />
namespace CHHC.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BeforeUserProfileTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BeforeUserProfileTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201404171842257_BeforeUserProfileTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
