// <auto-generated />
namespace CHHC.Web.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class InitMembership : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitMembership));
        
        string IMigrationMetadata.Id
        {
            get { return "201401190313414_InitMembership"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
